### ISSUE TITLE
Allowing for interpreter automation

### ISSUE THREAD

**Issue by c47s** [Sciman101/minefuck#2]
Consider allowing hoppers and droppers to insert and remove books from the interpreter's inventory. [This fabric tutorial](https://fabricmc.net/wiki/tutorial:inventory) might be helpful.

**Comment by Sciman101** [comment]
I hadn't considered this, I'll look into it when I can! It'd definitely improve their overall usefulness.

**Comment by Sciman101** [comment]
https://user-images.githubusercontent.com/19194867/115050156-74bae880-9ea9-11eb-8dd9-6244668ce880.mp4
Gonna test it a bit more, but it seems like it works!

**Comment by Sciman101** [comment]
Just published the [new version](https://modrinth.com/mod/minefck/version/ssgYSTuo), let me know if you run into any issues!

**Comment by c47s** [comment]
https://user-images.githubusercontent.com/36133719/115264677-83e9a280-a104-11eb-90c4-2069f546c8c4.mp4
Definitely seems to work. Here's a basic system made possible by the **new feature** that randomizes between 10 different programs.

Thank you for being an awesome mod author!
