### ISSUE TITLE
1.18.2?

### ISSUE THREAD

**Issue by walksanatora** [Sciman101/minefuck#6]
1.18 version (i havent checked if it works if you force it to load)

**Comment by Sciman101** [comment]
I haven't been doing much Minecraft dev as of late, but this is on my to do list at some point since people seem to want it. No promises as to when but I'll try to figure it out at some point soon

**Comment by walksanatora** [comment]
After just using `recaf` to modify the jar (just the fabric json) the mod runs just fine on 1.18.2 with no code changes
this is just a simple change of a number to get it working

**Comment by Sciman101** [comment]
Oh wait, it's that simple? Damn, sorry, I've been pretty distracted and haven't had time to mess with this. If it's that little work I'll try and push that

**Comment by walksanatora** [comment]
it's okay
I am also writing my own brainfuck derivitave 
. . . 
with memory pointers
IF/IF-ELSE blocks
and seperate memory spaces
. . .

**Comment by walksanatora** [comment]
my brainfuck is now on the esolangs wiki
[https://esolangs.org/wiki/YABFD](https://esolangs.org/wiki/YABFD)

**Comment by Sciman101** [comment]
Haven't been working on this mod at all, but very cool! Ended up stumbling onto YABFD by accident and noticing the reference to Minefuck.
